---

- hosts: all
  become: yes
  remote_user: root
  
  tasks:

  # - name: Include Rhel7
  #   include: playbooks/rhel7-tzdata.yml
  #   when: ansible_os_family == 'RedHat' and ansible_distribution_major_version > '6'
  #
  # - name: Include Rhel6
  #   include: playbooks/rhel6-tzdata.yml
  #   when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '6'

  - name: Include Rhel5
    include: playbooks/rhel-legacy-tzdata.yml
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version < '6'

  # - debug: var=zdump_rhel7.stdout_lines
  # - debug: var=zdump_rhel6.stdout_lines
  - debug: var=zdump_legacy.stdout_lines
