
- name: RHEL6 -> Copia TZData
  copy:
    src: "{{ item }}"
    dest: /tmp
    owner: root
  with_items:
      - rpms/tzdata-java-2018i-1.el6.noarch.rpm
      - rpms/tzdata-2018i-1.el6.noarch.rpm

- name: RHEL6 -> Install TZData
  yum:
    name: "/tmp/{{ item }}"
    state: present
  with_items:
      - tzdata-java-2018i-1.el6.noarch.rpm
      - tzdata-2018i-1.el6.noarch.rpm

- name: RHEL6 -> Check Time Zone
  shell: zdump -v /usr/share/zoneinfo/America/Santiago | grep 2019
  register: zdump_rhel6

# - debug: var=zdump_rhel6.stdout_lines
